
# returns the current sorted list of known stations
import operator

# crontab TIME format: 
# MIN HOUR DOM MON DOW CMD - "* * * * *"

def getStations(sortingKey):
    resp = [

    	   {
                "Address":  "Almelo, Netherlands 7606TJ",
                "Country":  "Netherlands",
                "Director": "Kegham Depoyan",
                "Email":    "info@radioarev.com",
                "Icon":     "https://static-media.streema.com/media/cache/14/34/14344378802ae3e87cb33f8f8c090f7d.png",
                "Name":     "Radio Arev",
                "Phone":    "+961 3 466 270",
                "Schedule": "* * * * *",
                "Url":      "http://cast6.asurahosting.com/proxy/radioare/stream",
                "Verified": "true",
                "Video":    "false",
                "WebPage":  "https://www.radioarev.com/radio.html"
                },
    	   {
                "Address":  "Beirut",
                "Country":  "Lebanon",
                "Director": "",
                "Email":    "yeridasartoutiantsayne@gmail.com",
                "Icon":     "https://cdn-profiles.tunein.com/s186962/images/logod.png?t=637037958650000000",
                "Name":     "Yeridasartoutyan Tsayny",
                "Phone":    "+961 76 464343",
                "Schedule": "* * * * *",
                "Url":      "http://65.108.98.93:8123/stream",
                "Verified": "true",
                "Video":    "false",
                "WebPage":  "https://yeridasartoutiantsayne.com/"
                },
    	   {
                "Address":  "0052 Nairi Zaryan str 22a, Yerevan, Armenia",
                "Country":  "Armenia",
                "Director": "",
                "Email":    "radioaurora@radioaurora.am",
                "Icon":     "https://radioaurora.am/ui/img/logo.png",
                "Name":     "Radio Aurora",
                "Phone":    "+37410 251007",
                "Schedule": "* * * * *",
                "Url":      "http://de.auroramedia.am/aurora.mp3",
                "Verified": "true",
                "Video":    "false",
                "WebPage":  "http://www.radioaurora.am"
                },
            {
                "Address":  "0052 Nairi Zaryan str 22a, Yerevan, Armenia",
                "Country":  "Armenia",
                "Director": "",
                "Email":    "radioaurora@radioaurora.am",
                "Icon":     "https://radioaurora.am/ui/img/logo.png",
                "Name":     "Radio Aurora Ser1",
                "Phone":    "+37410 251007",
                "Schedule": "* * * * *",
                "Url":      "http://am.radioaurora.am:8010/ser1.mp3",
                "Verified": "true",
                "Video":    "false",
                "WebPage":  "http://www.radioaurora.am"
                },
            {
                "Address":  "0052 Nairi Zaryan str 22a, Yerevan, Armenia",
                "Country":  "Armenia",
                "Director": "",
                "Email":    "radioaurora@radioaurora.am",
                "Icon":     "https://radioaurora.am/ui/img/logo.png",
                "Name":     "Radio Aurora Ser2",
                "Phone":    "+37410 251007",
                "Schedule": "* * * * *",
                "Url":      "http://am.radioaurora.am:8010/ser2.mp3",
                "Verified": "true",
                "Video":    "false",
                "WebPage":  "http://www.radioaurora.am"
                },
            {
                "Address":  "0052 Nairi Zaryan str 22a, Yerevan, Armenia",
                "Country":  "Armenia",
                "Director": "",
                "Email":    "radioaurora@radioaurora.am",
                "Icon":     "https://radioaurora.am/ui/img/logo.png",
                "Name":     "Radio Aurora Ser3",
                "Phone":    "+37410 251007",
                "Schedule": "* * * * *",
                "Url":      "http://am.radioaurora.am:8010/ser3.mp3",
                "Verified": "true",
                "Video":    "false",
                "WebPage":  "http://www.radioaurora.am"
                },
            {
                "Address":  "0052 Nairi Zaryan str 22a, Yerevan, Armenia",
                "Country":  "Armenia",
                "Director": "",
                "Email":    "radioaurora@radioaurora.am",
                "Icon":     "https://radioaurora.am/ui/img/logo.png",
                "Name":     "Radio Monte Carlo Armenia",
                "Phone":    "+37410 251007",
                "Schedule": "* * * * *",
                "Url":      "http://am.radioaurora.am:8010/montecarlo.mp3",
                "Verified": "true",
                "Video":    "false",
                "WebPage":  "http://www.radioaurora.am"
                },
            {
                # verified
                "Address":  "0025 Yerevan, Alex Manoogian 5 str",
                "Country":  "Armenia",
                "Director": "Armen Amiryan",
                "Email":    "aa@arradio.am",
                "Icon":     "https://cdn-profiles.tunein.com/s347439/images/logog.png?t=1",
                "Name":     "Yerevan FM",
                "Phone":    "+374-10-55-11-43",
                "Schedule": "* * * * *",
                "Url":      "http://eu1.stream4cast.com/proxy/arradioi/stream",
                "Verified": "true",
                "Video":    "false",
                "WebPage":  "http://www.yerevanfm.am/"
                },
            {
                "Address":  "Yerevan, Qochar 21",
                "Country":  "Armenia",
                "Director": "",
                "Email":    "impulse@impulse.am",
                "Icon":     "https://www.lratvakan.am/media/company/logo/corporate-logo_IAoQCpL.png",
                "Name":     "Lratvakan Radio",
                "Phone":    "+374 60 37 12 73",
                "Schedule": "* * * * *",
                "Url":      "http://212.34.233.78:8000/live",
                "Verified": "true",
                "Video":    "false",
                "WebPage":  "http://www.lratvakan.am/"
                },
            {
                "Address":  "",
                "Country":  "Armenia",
                "Director": "",
                "Email":    "info@lavradio.am",
                "Icon":     "https://www.lavradio.am/wp-content/uploads/2017/02/logo-1.png",
                "Name":     "Energy FM",
                "Phone":    "",
                "Schedule": "* * * * *",
                "Url":      "http://eu.stream4cast.com/proxy/energyfm/stream",
                "Verified": "true",
                "Video":    "false",
                "WebPage":  "http://www.lavradio.am"
                },
            {
                "Address":  "",
                "Country":  "Armenia",
                "Director": "",
                "Email":    "info@lavradio.am",
                "Icon":     "https://www.lavradio.am/wp-content/uploads/2017/02/logo-1.png",
                "Name":     "XFM Radio",
                "Phone":    "",
                "Schedule": "* * * * *",
                "Url":      "http://eu.stream4cast.com/proxy/xfmradio/stream",
                "Verified": "true",
                "Video":    "false",
                "WebPage":  "http://www.lavradio.am"
                },
            {
                "Address":  "",
                "Country":  "Armenia",
                "Director": "",
                "Email":    "info@lavradio.am",
                "Icon":     "https://www.lavradio.am/wp-content/uploads/2017/02/logo-1.png",
                "Name":     "MFM Music Radio",
                "Phone":    "",
                "Schedule": "* * * * *",
                "Url":      "http://eu.stream4cast.com/proxy/mfmradio/stream",
                "Verified": "true",
                "Video":    "false",
                "WebPage":  "http://www.lavradio.am"
                },
            { # verified!
                "Address":  "",
                "Country":  "Armenia",
                "Director": "Aghabek Margaryan",
                "Email":    "info@lavradio.am",
                "Icon":     "https://www.lavradio.am/wp-content/uploads/2017/02/logo-1.png",
                "Name":     "Lav Radio Mix",
                "Phone":    "+37455830003",
                "Schedule": "* * * * *",
                "Url":      "http://eu.stream4cast.com/proxy/lavradiomix/stream",
                "Verified": "true",
                "Video":    "false",
                "WebPage":  "http://www.lavradio.am"
                },
            { # verified!
                "Address":  "",
                "Country":  "Armenia",
                "Director": "Aghabek Margaryan",
                "Email":    "info@lavradio.am",
                "Icon":     "https://www.lavradio.am/wp-content/uploads/2017/02/logo-1.png",
                "Name":     "Lav Radio",
                "Phone":    "+37455830003",
                "Schedule": "* * * * *",
                "Url":      "http://eu.stream4cast.com/proxy/lavradio/stream",
                "Verified": "true",
                "Video":    "false",
                "WebPage":  "http://www.lavradio.am"
                },
            {
                # verified!
                "Address":  "Yerevan 25, Aleq Manukyan 5",
                "Country":  "Armenia",
                "Director": "Armen Amiryan",
                "Email":    "aa@arradio.am",
                "Icon":     "https://cdn.onlineradiobox.com/img/l/6/42836.v17.png",
                "Name":     "Public Radio of Armenia",
                "Phone":    "+374-10-55-11-43",
                "Schedule": "* * * * *",
                "Url":      "http://eu1.stream4cast.com/proxy/publicra/stream",
                "Verified": "true",
                "Video":    "false",
                "WebPage":  "http://www.armradio.am"
                },
            {
                "Address":  "4 rue Marcellin Berthelot 69150 DECINES",
                "Country":  "France",
                "Director": "",
                "Email":    "",
                "Icon":     "https://www.radioarmenie.com/images/logo-long.png",
                "Name":     "Radio Armenie",
                "Phone":    "04-78-49-52-74",
                "Schedule": "* * * * *",
                "Url":      "http://direct.radioarmenie.com:9029/stream",
                "Verified": "true",
                "Video":    "false",
                "WebPage":  "http://www.radioarmenie.com"
                },
            {
                "Address":  "41 rue des ecolses, 94140 Alfortville",
                "Country":  "France",
                "Director": "",
                "Email":    "",
                "Icon":     "https://radio-aypfm.com/assets/img/logo-header.png",
                "Name":     "Radio AYP",
                "Phone":    "01-43-53-19-90",
                "Schedule": "* * * * *",
                "Url":      "http://stric6.streamakaci.com/radioayp.mp3",
                "Verified": "true",
                "Video":    "false",
                "WebPage":  "http://radio-aypfm.com"
                },
            {
                "Address":  "",
                "Country":  "Armenia",
                "Director": "",
                "Email":    "",
                "Icon":     "https://radiohay.am/wp-content/uploads/2018/12/Logo-urish-chapi.png",
                "Name":     "Radio Hay (Yerevan)",
                "Phone":    "",
                "Schedule": "* * * * *",
                "Url":      "http://16242.cloudrad.io:9178/live",
                "Verified": "true",
                "Video":    "false",
                "WebPage":  "http://radiohay.am"
                },
            {
                "Address":  "",
                "Country":  "Armenia",
                "Director": "",
                "Email":    "info@radiojan.am",
                "Icon":     "https://cdn.onlineradiobox.com/img/l/3/72193.v8.png",
                "Name":     "Radio Jan",
                "Phone":    "+374-96-01-08-55",
                "Schedule": "* * * * *",
                "Url":      "http://s7.voscast.com:10258/radiojan",
                "Verified": "true",
                "Video":    "false",
                "WebPage":  "http://www.radiojan.am"
                },
            {
                "Address":  "Yerevan, Xandjyan 13a",
                "Country":  "Armenia",
                "Director": "",
                "Email":    "radiovan@radiovan.am",
                "Icon":     "https://radiovan.fm/css/images/radiovan.svg",
                "Name":     "Radio Van",
                "Phone":    "+374-10-54-00-01",
                "Schedule": "* * * * *",
                "Url":      "",
                "Verified": "false",
                "Video":    "false",
                "WebPage":  "http://radiovan.am"
                },
            {
                "Address":  "",
                "Country":  "",
                "Director": "",
                "Email":    "radioyan@imarmenian.com",
                "Icon":     "https://www.haykakanmusic.com/images/radio-yeraz.jpg",
                "Name":     "Radio Yeraz",
                "Phone":    "",
                "Schedule": "* * * * *",
                "Url":      "http://149.255.60.194:8008/stream",
                "Verified": "true",
                "Video":    "false",
                "WebPage":  "http://radioyeraz.com"
                },
            {
                "Address":  "",
                "Country":  "",
                "Director": "",
                "Email":    "",
                "Icon":     "https://triktrak.ca/wp-content/uploads/2015/07/Triktrak_LOGO_small.png",
                "Name":     "Trik Trak",
                "Phone":    "",
                "Schedule": "* * * * *",
                "Url":      "http://cast3.my-control-panel.com/proxy/triktrak/stream",
                "Verified": "true",
                "Video":    "false",
                "WebPage":  "http://triktrak.ca"
                },
            {
                "Address":  "Yerevan, Azatutyun Ave. 1/21",
                "Country":  "Armenia",
                "Director": "",
                "Email":    "info@vem.am",
                "Icon":     "https://vem.am/uploads/images/contents/24e2eedb71bf6569ae0c5e9daf3f7fac.svg",
                "Name":     "Vem Radio",
                "Phone":    "+374-10-54-88-70",
                "Schedule": "* * * * *",
                "Url":      "http://eu1.stream4cast.com/proxy/vemradio/stream",
                "Verified": "true",
                "Video":    "false",
                "WebPage":  "http://www.vem.am/"
                },
            {
                "Address":  "Center Shaghzoyan, 2nd Floor, Bourj Hammoud, Metn, Lebanon",
                "Country":  "Lebanon",
                "Director": "",
                "Email":    "info@voiceofvan.net",
                "Icon":     "https://www.voiceofvan.net/backend/uploads/setting/1723180428.png",
                "Name":     "Voice of Van",
                "Phone":    "+961-1-241272",
                "Schedule": "* * * * *",
                "Url":      "http://vovan.s3ming.com/vovan.mp3",
                "Verified": "true",
                "Video":    "false",
                "WebPage":  "http://www.voiceofvan.net/"
                },
            {
                # verified!
                "Address":  "3200 Wilshire Blvd. Ste 902NT, Los Angeles, CA, United States 90010",
                "Country":  "USA",
                "Director": "Sarkis Chakarian",
                "Email":    "info@yerevannights.com",
                "Icon":     "https://www.armenische-kirche.ch/wp-content/uploads/2013/02/yerevannights.jpg",
                "Name":     "Yerevan Nights",
                "Phone":    "+1-877-220-8951",
                "Schedule":"* * * * *",
                "Url":      "http://icecast.worldweb.services:80/Web",
                "Verified": "true",
                "Video":    "false",
                "WebPage":  "http://www.yerevannights.com"
                },
            {
                "Address":  "",
                "Country":  "Armenia",
                "Director": "",
                "Email":    "",
                "Icon":     "https://www.chanson.am/img/logo.png",
                "Name":     "Chanson AM",
                "Phone":    "",
                "Schedule": "* * * * *",
                "Url":      "http://eu.stream4cast.com/proxy/ulissesm/stream",
                "Verified": "true",
                "Video":    "false",
                "WebPage":  "https://www.chanson.am/"
                },
            {
                "Address":  "",
                "Country":  "Armenia",
                "Director": "",
                "Email":    "",
                "Icon":     "https://kissfm.am/ui/img/logo.png",
                "Name":     "Kiss FM",
                "Phone":    "",
                "Schedule": "* * * * *",
                "Url":      "http://ok.ru/video/664807546380",
                "Verified": "true",
                "Video":    "false",
                "WebPage":  "https://kissfm.am/en/home"
                },
            {
                "Address":  "",
                "Country":  "Armenia",
                "Director": "",
                "Email":    "info@radiomarshall.am",
                "Icon":     "https://www.radiomarshall.am/images/logo.png",
                "Name":     "Radio Marshall",
                "Phone":    "+374 11 540 840",
                "Schedule": "* * * * *",
                "Url":      "http://eu.stream4cast.com/proxy/marshallfm/stream",
                "Verified": "true",
                "Video":    "false",
                "WebPage":  "https://www.radiomarshall.am/"
                },
            {
                "Address":  "405 Waltham St. Lexington, MA 02421-7953",
                "Country":  "USA",
                "Director": "",
                "Email":    "setrag@bashde.org",
                "Icon":     "https://images.squarespace-cdn.com/content/v1/5803decb8419c2e5958aefc1/39f9708f-a54a-4e41-b76d-d18b81710d16/46409866_763017380715794_5630126075452325888_n.png?format=1500w",
                "Name":     "Bashde",
                "Phone":    "",
                "Schedule": "* * * * *",
                "Url":      "http://streams.radio.co/sa0bf8ec29/listen",
                "Verified": "true",
                "Video":    "false",
                "WebPage":  "https://bashde.org/"
                },
            {
                "Address":  "22a Nairi Zaryan St, Yerevan, Armenia",
                "Country":  "Armenia",
                "Director": "",
                "Email":    "info@radiojazzfm.am",
                "Icon":     "https://radiojazzfm.am/img/core-img/logo2.png",
                "Name":     "Radio Jazz FM",
                "Phone":    "",
                "Schedule": "* * * * *",
                "Url":      "http://de.auroramedia.am/jazz.mp3",
                "Verified": "true",
                "Video":    "false",
                "WebPage":  "https://radiojazzfm.am/en/home"
                },
            {
                "Address":  "375010 Yerevan, Tigran Mets 17",
                "Country":  "Armenia",
                "Director": "",
                "Email":    "",
                "Icon":     "https://www.radiofama.am/wp-content/uploads/lg8.png",
                "Name":     "Radio Fama",
                "Phone":    "+3741 59 70 00",
                "Schedule": "* * * * *",
                "Url":      "http://eu.stream4cast.com/proxy/rmirzakh/stream",
                "Verified": "true",
                "Video":    "false",
                "WebPage":  "https://www.radiofama.am/"
                },
            {
                "Address":  "80 Bigelow Ave, Watertown, MA 02472",
                "Country":  "USA",
                "Director": "",
                "Email":    "manager@hairenik.com",
                "Icon":     "https://hairenik.wpengine.com/wp-content/uploads/2014/10/haireniklogo2.png",
                "Name":     "Hairenik Radio",
                "Phone":    "+1-617-926-3974",
                "Schedule": "* * * * *",
                "Url":      "http://streaming.radio.co/sb64369622/listen",
                "Verified": "true",
                "Video":    "false",
                "WebPage":  "https://hairenik.com/"
                },
            {
                "Address":  "Yerevan, Lvovyan 1",
                "Country":  "Armenia",
                "Director": "",
                "Email":    "info@radiomariam.am",
                "Icon":     "https://www.radiomariam.am/resources/radiomariam/images/logo_white.png",
                "Name":     "Radio Mariam",
                "Phone":    "+374 93 72 33 32",
                "Schedule": "* * * * *",
                "Url":      "http://live.radiomariam.am/RadioMariam",
                "Verified": "true",
                "Video":    "false",
                "WebPage":  "https://www.radiomariam.am/"
                },
            {
                "Address":  "Yerevan, Antarnain Street 188/16",
                "Country":  "Armenia",
                "Director": "",
                "Email":    "office@1055.am",
                "Icon":     "https://1055.am/wp-content/uploads/2019/02/Logo-1055-spitak-tarer1.png",
                "Name":     "FM 105.5",
                "Phone":    "+374 10 560000",
                "Schedule": "* * * * *",
                "Url":      "http://audio.cloudrad.io/3745421d/live",
                "Verified": "true",
                "Video":    "false",
                "WebPage":  "https://1055.am/"
                },
            {
                "Address":  "",
                "Country":  "Armenia",
                "Director": "",
                "Email":    "",
                "Icon":     "https://armgospelradio.com/images/logo_blue_1.png",
                "Name":     "Armenian Gospel Radio",
                "Phone":    "+374 94 222 173",
                "Schedule": "* * * * *",
                "Url":      "http://s8.myradiostream.com/15554/listen.mp3",
                "Verified": "true",
                "Video":    "false",
                "WebPage":  "https://armgospelradio.com/"
                },
            {
                "Address":  "Beirut, Lebanon",
                "Country":  "Lebanon",
                "Director": "",
                "Email":    "",
                "Icon":     "https://www.radioyan.com/wp-content/uploads/2015/09/radioyanlight-190-60.png",
                "Name":     "Radio YAN",
                "Phone":    "",
                "Schedule": "* * * * *",
                "Url":      "http://237.185.153.160.host.secureserver.net/proxy/radioyan1/stream",
                "Verified": "true",
                "Video":    "false",
                "WebPage":  "https://www.radioyan.com/"
                },
            {
                "Address":  "",
                "Country":  "Armenia",
                "Director": "",
                "Email":    "",
                "Icon":     "https://proxy.zeno.fm/content/stations/agxzfnplbm8tc3RhdHNyMgsSCkF1dGhDbGllbnQYgICInriwuAgMCxIOU3RhdGlvblByb2ZpbGUYgICI3rCdqAsMogEEemVubw/image/?u=1711575067000",
                "Name":     "Radio Azalia",
                "Phone":    "",
                "Schedule": "* * * * *",
                "Url":      "http://stream.zeno.fm/bvd0260v7hhvv",
                "Verified": "true",
                "Video":    "false",
                "WebPage":  "https://zeno.fm/radio/azalia/"
                },
            {
                "Address":  "",
                "Country":  "Armenia",
                "Director": "",
                "Email":    "",
                "Icon":     "",
                "Name":     "Radio Sputnik Armenia",
                "Phone":    "",
                "Schedule": "* * * * *",
                "Url":      "",
                "Verified": "false",
                "Video":    "false",
                "WebPage":  "https://arm.sputniknews.ru/radio/"
                },
            {
                "Address":  "",
                "Country":  "USA",
                "Director": "",
                "Email":    "",
                "Icon":     "https://radio.mwvhost.com/storage/images/StreamLogo/logo_1764370067.png",
                "Name":     "Radio Jan USA",
                "Phone":    "+1 818 712-1211",
                "Schedule": "* * * * *",
                "Url":      "https://s4.voscast.com:8865/stream",
                "Verified": "true",
                "Video":    "false",
                "WebPage":  "https://www.radiojan.com/"
                },
            {
                "Address":  "Gyumri Railway Station 2 Floor",
                "Country":  "Armenia",
                "Director": "",
                "Email":    "radiovan.gyumri1@gmail.com",
                "Icon":     "https://radiovangyumri.am/wp-content/uploads/2022/05/0079photo_2025-10-29_03-48-28-e1761695728581.jpg",
                "Name":     "Radio Van Gyumri",
                "Phone":    "+374 95 194344",
                "Schedule": "* * * * *",
                "Url":      "http://a13.asurahosting.com/listen/radio_van_gyumri/radio.mp3",
                "Verified": "true",
                "Video":    "false",
                "WebPage":  "https://radiovangyumri.am/"
                },
            {
                "Address":  "",
                "Country":  "Armenia",
                "Director": "",
                "Email":    "",
                "Icon":     "https://autoradio.am/images/LOGO%20Autoradio.png",
                "Name":     "Avto Radio",
                "Phone":    "",
                "Schedule": "* * * * *",
                "Url":      "http://de.auroramedia.am/autoradio",
                "Verified": "true",
                "Video":    "false",
                "WebPage":  "https://autoradio.am/"
                },
            {
                "Address":  "",
                "Country":  "Armenia",
                "Director": "",
                "Email":    "",
                "Icon":     "https://proxy.zeno.fm/content/stations/6bf108f4-9add-495b-8eac-a9164270d38b/image/?u=1730141126000",
                "Name":     "Radio Kavkaz",
                "Phone":    "",
                "Schedule": "* * * * *",
                "Url":      "http://stream.zeno.fm/y4b9z1qbya3uv",
                "Verified": "true",
                "Video":    "false",
                "WebPage":  "https://zeno.fm/radio/radio-kavkaz/"
                },
            {
                "Address":  "",
                "Country":  "UAE",
                "Director": "",
                "Email":    "radioayk@gmail.com",
                "Icon":     "https://static.wixstatic.com/media/b1dfa3_be9e61c7b63b9cafdaa5275c3285ca55.png/v1/crop/x_4,y_0,w_321,h_126/fill/w_365,h_140,al_c,lg_1,q_85,enc_avif,quality_auto/RADIO-AYK-HTML-WEB-LOGO.png",
                "Name":     "Radio AYK",
                "Phone":    "",
                "Schedule": "* * * * *",
                "Url":      "http://64.150.176.42:8117/listen.mp3",
                "Verified": "true",
                "Video":    "false",
                "WebPage":  "https://www.radioayk.com/"
                },
            {
                "Address":  "Rue Maraash, Bourj Hammoud",
                "Country":  "Lebanon",
                "Director": "",
                "Email":    "",
                "Icon":     "https://radioyan.com/arf-radio/wp-content/uploads/2021/06/cropped-radioyanpatriotic.png",
                "Name":     "ARF Radio",
                "Phone":    "+961 3 274 847",
                "Schedule": "* * * * *",
                "Url":      "http://237.185.153.160.host.secureserver.net/proxy/radioyan2/stream",
                "Verified": "true",
                "Video":    "false",
                "WebPage":  "https://radioyan.com/arf-radio/"
                },
            {
                "Address":  "",
                "Country":  "Armenia",
                "Director": "",
                "Email":    "",
                "Icon":     "",
                "Name":     "Europa Plus Armenia",
                "Phone":    "",
                "Schedule": "* * * * *",
                "Url":      "http://de.auroramedia.am/europaplus",
                "Verified": "true",
                "Video":    "false",
                "WebPage":  ""
                },
            {
                "Address":  "",
                "Country":  "Armenia",
                "Director": "",
                "Email":    "",
                "Icon":     "https://arevik.armradio.am/wp-content/uploads/2020/01/new-web-logo.png",
                "Name":     "Radio Arevik",
                "Phone":    "",
                "Schedule": "* * * * *",
                "Url":      "",
                "Verified": "false",
                "Video":    "false",
                "WebPage":  "https://arevik.armradio.am/"
                },
            {
                "Address":  "",
                "Country":  "Armenia",
                "Director": "",
                "Email":    "",
                "Icon":     "https://mshakuyt.armradio.am/wp-content/uploads/2021/05/radio-mshakuyt-logo.svg",
                "Name":     "Radio Mshakuyt",
                "Phone":    "",
                "Schedule": "* * * * *",
                "Url":      "",
                "Verified": "false",
                "Video":    "false",
                "WebPage":  "https://mshakuyt.armradio.am/"
                },
            {
                "Address":  "",
                "Country":  "Armenia",
                "Director": "",
                "Email":    "",
                "Icon":     "https://imradio.armradio.am/wp-content/uploads/2021/09/imagemeta2.png",
                "Name":     "Im Radio",
                "Phone":    "",
                "Schedule": "* * * * *",
                "Url":      "",
                "Verified": "false",
                "Video":    "false",
                "WebPage":  "https://imradio.armradio.am/"
                },
            {
                "Address":  "",
                "Country":  "Armenia",
                "Director": "",
                "Email":    "",
                "Icon":     "https://journews.am/wp-content/uploads/2021/09/LOGO-3.png",
                "Name":     "Journews Radio",
                "Phone":    "",
                "Schedule": "* * * * *",
                "Url":      "http://stream.zeno.fm/dvodr8cuwc5uv",
                "Verified": "true",
                "Video":    "false",
                "WebPage":  "https://journews.am/"
                },
            {
                "Address":  "",
                "Country":  "Lebanon",
                "Director": "",
                "Email":    "",
                "Icon":     "https://www.radio.net/300/hayazgidzayn.png",
                "Name":     "Hayazgi Dzayn",
                "Phone":    "",
                "Schedule": "* * * * *",
                "Url":      "http://c7.radioboss.fm:18299/stream",
                "Verified": "true",
                "Video":    "false",
                "WebPage":  ""
                },
            {
                "Address":  "",
                "Country":  "Russia",
                "Director": "",
                "Email":    "",
                "Icon":     "https://101.ru/design/images/new/logo.png",
                "Name":     "101.ru Armenia",
                "Phone":    "",
                "Schedule": "* * * * *",
                "Url":      "",
                "Verified": "false",
                "Video":    "false",
                "WebPage":  "https://armenia.101.ru"
                },
            {
                "Address":  "",
                "Country":  "Belgium",
                "Director": "",
                "Email":    "belgahay@gmail.com",
                "Icon":     "https://usercontent.one/wp/belgahay.be/wp-content/uploads/2022/10/belgahay-logo-web-1.png",
                "Name":     "Belgahay",
                "Phone":    "+32 483 327 229",
                "Schedule": "* * * * *",
                "Url":      "http://streamer.radio.co/sa1357f891/listen",
                "Verified": "true",
                "Video":    "false",
                "WebPage":  "https://belgahay.be/"
                },
            {
                "Address":  "Los Angeles, California",
                "Country":  "USA",
                "Director": "",
                "Email":    "",
                "Icon":     "https://www.hyejams.com/assets/hyejamslogo.png",
                "Name":     "Hye Jams Radio",
                "Phone":    "424-416-1577",
                "Schedule": "* * * * *",
                "Url":      "",
                "Verified": "false",
                "Video":    "false",
                "WebPage":  "https://www.hyejams.com/"
                },
            {
                "Address":  "Yerevan, Khandjyan Street 13a",
                "Country":  "Armenia",
                "Director": "",
                "Email":    "info@rusradio.am",
                "Icon":     "https://rusradio.am/assets/images/logo.png",
                "Name":     "Русское Радио Армения",
                "Phone":    "+374 10 58 58 50",
                "Schedule": "* * * * *",
                "Url":      "http://rusradioreg.webcaramba.com/yerevan.rusradio128.mp3",
                "Verified": "true",
                "Video":    "false",
                "WebPage":  "https://rusradio.am/"
                },
            {
                "Address":  "Vanadzor, Abelyan 46a",
                "Country":  "Armenia",
                "Director": "",
                "Email":    "lorumig@gmail.com",
                "Icon":     "https://migfm.am/wp-content/uploads/2023/10/cropped-Mig_TVR_Logo_N-removebg-preview-300x180.png",
                "Name":     "Mig FM",
                "Phone":    "+374 77 98 07 17",
                "Schedule": "* * * * *",
                "Url":      "",
                "Verified": "false",
                "Video":    "false",
                "WebPage":  "https://migfm.am/"
                },
            {
                "Address":  "Los Angeles, California",
                "Country":  "USA",
                "Director": "Messig Tchouldjian",
                "Email":    "",
                "Icon":     "https://cdn-profiles.tunein.com/s302750/images/logod.png?t=636504983287970000",
                "Name":     "Radio Hyestars",
                "Phone":    "",
                "Schedule": "* * * * *",
                "Url":      "http://cast3.asurahosting.com/proxy/meesya/stream",
                "Verified": "true",
                "Video":    "false",
                "WebPage":  "https://www.radiohyestars.com/"
                },
            {
                "Address":  "Los Angeles, California",
                "Country":  "USA",
                "Director": "",
                "Email":    "laarmenianradio@yahoo.com",
                "Icon":     "",
                "Name":     "LA Armenian Radio",
                "Phone":    "",
                "Schedule": "* * * * *",
                "Url":      "http://cast.thiff.com/proxy/laarmeni?mp=/stream",
                "Verified": "true",
                "Video":    "false",
                "WebPage":  "https://www.laarmenianradio.com/"
                },
            {
                "Address":  "Northern Prospekt 1, Yerevan",
                "Country":  "Armenia",
                "Director": "",
                "Email":    "info@cityfm.am",
                "Icon":     "https://onlineradiobox.ru/media180/cityfm.webp",
                "Name":     "Сити-ФМ Ереван 106.0",
                "Phone":    "+374 10 538087",
                "Schedule": "* * * * *",
                "Url":      "http://icecast-rian.cdnvideo.ru/voicearm1",
                "Verified": "true",
                "Video":    "false",
                "WebPage":  "https://fm106.am/"
                },
            {
                "Address":  "0052 Nairi Zaryan str 22a, Yerevan",
                "Country":  "Armenia",
                "Director": "",
                "Email":    "",
                "Icon":     "https://radioroks.am/images/logo.jpg",
                "Name":     "Radio Roks",
                "Phone":    "8077",
                "Schedule": "* * * * *",
                "Url":      "http://am.radioaurora.am:8010/roks.mp3",
                "Verified": "true",
                "Video":    "false",
                "WebPage":  "https://radioroks.am/"
                },
            {
                "Address":  "",
                "Country":  "Turkey",
                "Director": "",
                "Email":    "",
                "Icon":     "https://www.norradyo.com/wp-content/uploads/2025/12/cropped-nor-radyo-logo.jpg",
                "Name":     "Nor Radyo",
                "Phone":    "",
                "Schedule": "* * * * *",
                "Url":      "",
                "Verified": "false",
                "Video":    "false",
                "WebPage":  "https://www.norradyo.com/"
                },
            {
                "Address":  "Southern California",
                "Country":  "USA",
                "Director": "",
                "Email":    "",
                "Icon":     "https://armenianbiblestudy.com/wp-content/uploads/2021/07/ABS-Logo.png",
                "Name":     "Armenian Bible Study",
                "Phone":    "",
                "Schedule": "* * * * *",
                "Url":      "https://ssl.nexuscast.com:8082/stream?type=http",
                "Verified": "true",
                "Video":    "false",
                "WebPage":  "https://armenianbiblestudy.com/radio/"
                },
            {
                "Address":  "Yerevan, Armenia",
                "Country":  "Armenia",
                "Director": "",
                "Email":    "loveradioyerevan@gmail.com",
                "Icon":     "https://cdn.onlineradiobox.com/img/l/8/68078.v4.png",
                "Name":     "Love Radio",
                "Phone":    "+374 55 787041",
                "Schedule": "* * * * *",
                "Url":      "https://loveradio.streamingmedia.it/play",
                "Verified": "true",
                "Video":    "false",
                "WebPage":  "http://www.loveradio.am"
                },
            {
                "Address":  "Yerevan 93.7 FM",
                "Country":  "Armenia",
                "Director": "",
                "Email":    "",
                "Icon":     "https://top-radio.ru/assets/image/radio/180/radiomir.jpg",
                "Name":     "Radio MIR Armenia",
                "Phone":    "",
                "Schedule": "* * * * *",
                "Url":      "http://46.162.206.108:8000/live.mp3",
                "Verified": "true",
                "Video":    "false",
                "WebPage":  "https://radiomir.fm/regions/armeniya"
                },
            {
                "Address":  "32 rue Pompéry, 26500 Bourg-Lès-Valence",
                "Country":  "France",
                "Director": "",
                "Email":    "radio.a@wanadoo.fr",
                "Icon":     "https://radioa.net/wp-content/uploads/2021/06/cropped-Radio-A-cover-2018-300x108.jpeg",
                "Name":     "Radio A 97.8",
                "Phone":    "+33 4 75 56 18 33",
                "Schedule": "* * * * *",
                "Url":      "http://stream.votreradiosurlenet.eu/radioa.mp3",
                "Verified": "true",
                "Video":    "false",
                "WebPage":  "https://radioa.net/"
                }
            ]
    if sortingKey not in ("Name", "Country", "Video"):
        sortingKey = "Name"
    resp.sort(key=operator.itemgetter(sortingKey))
    return resp
